#! /usr/bin/perl -w

# by Zbigniew Karolczuk, updated 20 July 2015
# Configuration page for all scripts related to CABLE STRIKE tool

# NUMBER OF CHANNELS ON STREAMER
  $trce=000;

# PATH TO LIBRI LED WHERE THE CABLE STRIKES ARE EDITED
  $led="edition library directory";

# SET UNIQUE PHRASE AT LED WHERE PROGRAM WILL START LOOKING FOR CABLE STRIKES (NO WILD CHARACTERS!)
  $begn="EDITIONS FOR CABLE STRIKES ALWAYS BELOW HERE !!";

# SET UNIQUE PHRASE AT LED WHERE PROGRAM WILL STOP SEARCHING FOR HIT NOISE (NO WILD CHARACTERS!)
  $fnsh="edition flag";

# HOW MANY EDITED TRACES WILL BE DISPLAYED AS A SEPARATE CHANNELS FOR ONE SHOT? 
# IF EDITED MANY CONSECUTIVE CHANNELS, THE SCRIPT WILL OUTPUT A RANGE IF FOUND MORE ADJACENT TRACES
  $rngc=00;

# DATA PROCESSING CONDITION. HOW MANY TRACES ARE ALLOWED TO EDIT FOR ONE CABLE AND ONE SHOT?
  $okld=000; 

# DATA PROCESSING CONDITION. HOW MANY ADJACENT TRACES ARE ALLOWED TO EDIT FOR ONE CABLE AND ONE SHOT?
  $badc=000;

